### ISSUE TITLE
Development environment

### ISSUE THREAD

**Issue by APeP-Electronics** [ehrenberdg/OrCAD2KiCADtranslator#1]
Having the same problem, I find that converting the Tango netlist into the S expression format used by KiCAD is very useful.
To use test2.c it would be useful to know which environment / compiler it was written with.
I used various environments / compilers: the one that gave me fewer errors was CodeBlocks, but it seems that the exit () function is missing.
It would be useful to put it in the repository.

**Comment by ehrenberdg** [comment]
APeP(?), I used the developer's prompt on MicroSoft's Visual Studio 2019 to do the development work on _test2.c_ -- thus avoiding the learning curve on the Visual Studio tool. I'm not a professional software developer and I had to think about how I did the compile step back in January of this year (2021). I keep trying **cc filename**. In MicroSoft's world it's **cl filename**. (This dates me, I'm a Unix user back to my college days in the late'70s). 

As for the missing _exit()_ I suspect any C programming environment has the equivalent function.

In a pinch, a test editor (I like _vim_) could do the Tango to KiCAD translations., thou perhaps a bit tedious.

A simple schematic created in OrCAD and and netlist generated with the Tango tool will reveal the structure of the netlist generated by OrCAD. Similarly, the KiCAD tool can be used to reveal the S structure of the tool's netlist generator.  Beware: The KiCAD tool cannot handle embedded whitespace in the value field generated by OrCAD, i.e. <1uf 50V> will choke KiCAD -- <1uf50V> will work.

I think I generated the necessary boilerplate at the head of the KiCAD netlist from within _test2.c_, but the embedded software version number may become dated and might need touching up -- a text editor could do this simple task (on the output file) without recompiling the program.

David Ehrenberg
28apr2021
ehrenberDG@gmail.com
